import tomllib
from pathlib import Path


def load_profile(name, base=Path("profiles")):
    data = tomllib.loads((Path(base) / f"{name}.toml").read_text())
    data.setdefault("mods", [])
    return data


def load_lock(path):
    p = Path(path)
    if not p.exists():
        return {}
    return tomllib.loads(p.read_text())


def set_mod(lock, mod_id, version, asset, sha256, source):
    lock[mod_id] = {
        "version": version, "asset": asset, "sha256": sha256, "source": source,
    }


def _toml_escape(s):
    # Backslash first — it's the escape char, so escaping it after the others
    # would double-escape their inserted backslashes. tomllib rejects raw
    # control chars inside a basic string, so newline/CR/tab must go too or the
    # lockfile won't round-trip.
    return (
        str(s)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def write_lock(path, data):
    lines = ["# Generated by erm. Pinned mod versions + hashes.", ""]
    for mod_id in sorted(data):
        lines.append(f"[{mod_id}]")
        for key in ("version", "asset", "sha256", "source"):
            if key in data[mod_id]:
                lines.append(f'{key} = "{_toml_escape(data[mod_id][key])}"')
        lines.append("")
    Path(path).write_text("\n".join(lines))
