import tomllib
from pathlib import Path

from .errors import PathError


def load_profile(name, base=Path("profiles"), _seen=None):
    """Load a profile, resolving an optional `includes = ["other", ...]` list.

    Included profiles are merged in first (in include order), then this
    profile's own `[[mods]]`. On a duplicate mod id the entry defined LATEST
    wins — a later include, or this profile's own entry, overrides an earlier
    one — so a profile can both compose others and override individual mods.
    A cycle in the include graph, or an unknown included profile, raises
    PathError. Callers already wrap a missing top-level profile.

    Also resolves an optional `excludes = ["other-profile", ...]` list — names
    of profiles this one is mutually exclusive with (e.g. two stacks that both
    edit regulation.bin). The resolved `excludes` is the union of every
    included profile's `excludes` plus this profile's own, de-duplicated,
    order-stable — so a profile that includes another inherits its excludes
    too, without having to repeat them.
    """
    base = Path(base)
    _seen = _seen or ()
    if name in _seen:
        raise PathError("profile include cycle: " + " -> ".join(_seen + (name,)))
    data = tomllib.loads((base / f"{name}.toml").read_text())
    merged, index = [], {}
    excludes, excludes_seen = [], set()

    def add(mod):
        mid = mod["id"]
        if mid in index:
            merged[index[mid]] = mod          # latest definition wins, in place
        else:
            index[mid] = len(merged)
            merged.append(mod)

    def add_exclude(exc_name):
        if exc_name not in excludes_seen:
            excludes_seen.add(exc_name)
            excludes.append(exc_name)

    for inc in data.get("includes", []):
        try:
            included = load_profile(inc, base, _seen + (name,))
        except OSError as exc:
            raise PathError(f"profile '{name}' includes unknown profile '{inc}': {exc}") from exc
        for m in included["mods"]:
            add(m)
        for exc_name in included.get("excludes", []):
            add_exclude(exc_name)
    for m in data.get("mods", []):
        add(m)
    for exc_name in data.get("excludes", []):
        add_exclude(exc_name)
    data["mods"] = merged
    data["excludes"] = excludes
    return data


def load_lock(path):
    p = Path(path)
    if not p.exists():
        return {}
    return tomllib.loads(p.read_text())


def set_mod(lock, mod_id, version, asset, sha256, source):
    lock[mod_id] = {
        "version": version, "asset": asset, "sha256": sha256, "source": source,
    }


def _toml_escape(s):
    # Backslash first — it's the escape char, so escaping it after the others
    # would double-escape their inserted backslashes. tomllib rejects raw
    # control chars inside a basic string, so newline/CR/tab must go too or the
    # lockfile won't round-trip.
    return (
        str(s)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def write_lock(path, data):
    lines = ["# Generated by erm. Pinned mod versions + hashes.", ""]
    for mod_id in sorted(data):
        lines.append(f"[{mod_id}]")
        for key in ("version", "asset", "sha256", "source"):
            if key in data[mod_id]:
                lines.append(f'{key} = "{_toml_escape(data[mod_id][key])}"')
        lines.append("")
    Path(path).write_text("\n".join(lines))
